trigger:
  branches:
    include:
      - features/pipelines

resources:
  containers:
    - container: 'sql_ci'
      image: pwsacrsqldevops.azurecr.io/testdb:2
      options: -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=HJkds*(pvdhsiuh289pV" --expose 1433
      endpoint: 'pwsacrsqldevops'

jobs:
  - job: 
    pool:
      vmImage: windows-latest
    steps:
    - task: MSBuild@1
      displayName: 'DACPAC build'
      inputs:
        solution: '$(System.DefaultWorkingDirectory)/db/test/test.sln'

    - task: CopyFiles@2
      displayName: 'Copy DACPACs'
      inputs:
        cleanTargetFolder: false
        sourceFolder: '$(System.DefaultWorkingDirectory)/db/test/bin/Debug/'
        contents: '*.dacpac'
        targetFolder: '$(build.artifactstagingdirectory)'

    - publish: '$(build.artifactstagingdirectory)'
      artifact: drop

  - job: RunInContainer
    pool:
      vmImage: 'ubuntu-18.04'
    container: 'sql_ci'
    steps:
      - download: current
        artifact: drop
      - task: Bash@3
        env:
          WORKINGDIR:  $(Pipeline.Workspace)
        inputs:
          script: |
            [[ -f /opt/sqlpackage/sqlpackage ]] && echo "sqlpackage exists!"
            [[ -f $WORKINGDIR/drop/test.dacpac ]] && echo "sqlpackage exists!"
    