trigger:
  branches:
    include:
      - features/pipelines

jobs:
  # - job: BuildDacpac
  #   pool:
  #     vmImage: windows-latest
  #   steps:
  #   - task: MSBuild@1
  #     displayName: 'DACPAC build'
  #     inputs:
  #       solution: '$(System.DefaultWorkingDirectory)/db/test/test.sln'

  #   - task: CopyFiles@2
  #     displayName: 'Copy DACPACs'
  #     inputs:
  #       cleanTargetFolder: false
  #       sourceFolder: '$(System.DefaultWorkingDirectory)/db/test/bin/Debug/'
  #       contents: '*.dacpac'
  #       targetFolder: '$(build.artifactstagingdirectory)'

  #   - publish: '$(build.artifactstagingdirectory)'
  #     artifact: drop

  - job: TestDacpac
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: PowerShell@2
        displayName: Install SqlPackage
        inputs:
          targetType: 'filePath'
          filePath: '$(System.DefaultWorkingDirectory)\pipelines\Get-SqlPackage.ps1'
      - task: PowerShell@2
        displayName: Deploy Dacpac
        inputs:
          targetType: 'filePath'
          arguments: -sqlUserName sa -sqlUserPassword "HJkds*(pvdhsiuh289pV" -sqlServerName pws-aci-sqldevops.australiaeast.azurecontainer.io -databaseName test -dacpacPath $(System.DefaultWorkingDirectory)\test.dacpac -sqlPackagePath $(SqlPackagePath)
          filePath: '$(System.DefaultWorkingDirectory)\pipelines\Publish-Dacpac.ps1'
