trigger:
  branches:
    include:
      - features/pipelines

resources:
  containers:
    - container: 'sql_ci'
      image: pwsacrsqldevops.azurecr.io/testdb:2
      options: -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=HJkds*(pvdhsiuh289pV" --expose 1433 --user 0:0
      endpoint: 'pwsacrsqldevops'

jobs:
  - job: BuildDacpac
    pool:
      vmImage: windows-latest
    steps:
    - task: MSBuild@1
      displayName: 'DACPAC build'
      inputs:
        solution: '$(System.DefaultWorkingDirectory)/db/test/test.sln'

    - task: CopyFiles@2
      displayName: 'Copy DACPACs'
      inputs:
        cleanTargetFolder: false
        sourceFolder: '$(System.DefaultWorkingDirectory)/db/test/bin/Debug/'
        contents: '*.dacpac'
        targetFolder: '$(build.artifactstagingdirectory)'

    - publish: '$(build.artifactstagingdirectory)'
      artifact: drop

  - job: TestDacpac
    dependsOn: BuildDacpac
    condition: succeeded()
    pool:
      vmImage: 'ubuntu-18.04'
    container: 'sql_ci'
    steps:
      - download: current
        artifact: drop
      - task: Bash@3
        env:
          WORKINGDIR: $(Pipeline.Workspace)
        inputs:
          targetType: inline
          workingDirectory: $(Pipeline.Workspace)
          script: |
            echo $WORKINGDIR
            [[ -f /opt/sqlpackage/sqlpackage ]] && echo "sqlpackage exists!"
            [[ -f $WORKINGDIR/drop/test.dacpac ]] && echo "dacpac exists!"
            ( /opt/mssql/bin/sqlservr & ) | grep -q "Service Broker manager has started" \
            /opt/sqlpackage/sqlpackage /a:Publish /tsn:. /tdn:test /tu:sa /tp:HJkds*(pvdhsiuh289pV /sf:$WORKINGDIR/test.dacpac
    